name: RealisticSleep
version: "${version}"
author: [sideways_sky, MasterKorawith]
description: A plugin that makes sleeping more realistic, forked from sideways_sky by MasterKorawith.
main: net.sideways_sky.realisticsleep.RealisticSleep
api-version: "1.20"
